###
GET http://localhost:8080/rtc/test/publisher/uid/1
Content-Type: application/json

###
GET http://localhost:8080/ping
Content-Type: application/json

###
GET http://localhost:8080/testing
Content-Type: application/json